{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurallm.fullname" . }}
  labels:
    {{- include "aurallm.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "aurallm.databaseUrl" . | quote }}
  {{- if or .Values.redis.enabled .Values.externalRedis.url }}
  REDIS_URL: {{ include "aurallm.redisUrl" . | quote }}
  {{- end }}
{{- end }}